### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by willis7** [onsi/gomega#202]
Whilst trying to use `Eventually` from the async library I hit a panic:

```
--- FAIL: TestJoinAndLoseWithoutBidding (1.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11c9ae5]

goroutine 20 [running]:
testing.tRunner.func1(0xc420082820)
	/usr/local/Cellar/go/1.8/libexec/src/testing/testing.go:622 +0x55f
panic(0x1200e80, 0x13232d0)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 +0x2f0
github.com/willis7/fifty-cal/vendor/github.com/onsi/gomega/internal/asyncassertion.(*AsyncAssertion).match.func1(0x1228d88, 0x9)
	/Users/sionix/Code/go/src/github.com/willis7/fifty-cal/vendor/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go:133 +0x565
github.com/willis7/fifty-cal/vendor/github.com/onsi/gomega/internal/asyncassertion.(*AsyncAssertion).match(0xc420081080, 0x13127e0, 0xc42007ae40, 0xc42002d601, 0x0, 0x0, 0x0, 0x11d5001)
	/Users/sionix/Code/go/src/github.com/willis7/fifty-cal/vendor/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go:155 +0x4de
github.com/willis7/fifty-cal/vendor/github.com/onsi/gomega/internal/asyncassertion.(*AsyncAssertion).Should(0xc420081080, 0x13127e0, 0xc42007ae40, 0x0, 0x0, 0x0, 0xc420081080)
	/Users/sionix/Code/go/src/github.com/willis7/fifty-cal/vendor/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go:47 +0x77
github.com/willis7/fifty-cal/cmd.TestJoinAndLoseWithoutBidding(0xc420082820)
	/Users/sionix/Code/go/src/github.com/willis7/fifty-cal/cmd/main_test.go:14 +0x1d4
testing.tRunner(0xc420082820, 0x1232008)
	/usr/local/Cellar/go/1.8/libexec/src/testing/testing.go:657 +0x108
created by testing.(*T).Run
	/usr/local/Cellar/go/1.8/libexec/src/testing/testing.go:697 +0x544
FAIL	github.com/willis7/fifty-cal/cmd	1.039s
make: *** [race] Error 1
```

I have created a branch for replicating the bug, here:
https://github.com/willis7/fifty-cal/tree/bug/gomega

**Comment by onsi** [comment]
It looks like you didn't register the `testing.T` with Gomega:

https://github.com/onsi/gomega/blob/master/gomega_dsl.go#L47-L64

**Comment by willis7** [comment]
Thanks for the prompt reply, that has certainly got me further.

Lesson learnt to read the full documentation next time.
