### ISSUE TITLE
gexec: Start panics with non-pointer receiver implementation of io.Writer

### ISSUE THREAD

**Issue by Bo0mer** [onsi/gomega#227]
# My setup
```
go version go1.9 darwin/amd64
```
Gomega version - `dcabb60a477c2b6f456df65037cb6708210fbb02`

# What I did
I run the program bellow (link to playground - https://play.golang.org/p/AF6vrN9IWs).

```go
package main

import (
	"os/exec"

	"github.com/onsi/gomega/gexec"
)

func main() {
	var d discard
	gexec.Start(exec.Command("whoami"), d, d)
}

type discard int

func (d discard) Write(p []byte) (int, error) {
	return len(p), nil
}
```

# What I expected to happen
The program exits cleanly.
# What actually happens
Panic.
```
panic: reflect: call of reflect.Value.IsNil on int Value

goroutine 1 [running]:
reflect.Value.IsNil(0x1101ba0, 0x129ee60, 0x82, 0x129ee60)
	/usr/local/go/src/reflect/value.go:995 +0x12e
github.com/onsi/gomega/gexec.Start(0xc4200bc160, 0x11d16a0, 0x129ee60, 0x11d16a0, 0x129ee60, 0x0, 0x0, 0x0)
	/Users/ivan/workspace/Go/src/github.com/onsi/gomega/gexec/session.go:81 +0x21a
main.main()
	/tmp/gexec/main.go:11 +0xef
exit status
```

The panic is caused by the following lines[0], since calling `IsNil` on non-pointers does not make sense.
```go
	if outWriter != nil && !reflect.ValueOf(outWriter).IsNil() {
		commandOut = io.MultiWriter(commandOut, outWriter)
	}

	if errWriter != nil && !reflect.ValueOf(errWriter).IsNil() {
		commandErr = io.MultiWriter(commandErr, errWriter)
	}
```

I can look into submitting a PR if you're ok with that.
Thanks,
Ivan

[0] https://github.com/onsi/gomega/blob/master/gexec/session.go#L81

**Comment by Bo0mer** [comment]
Changing the code above to
```go
	if outWriter != nil {
		switch reflect.ValueOf(outWriter).Kind() {
		case reflect.Ptr:
			if !reflect.ValueOf(outWriter).IsNil() {
				commandOut = io.MultiWriter(commandOut, outWriter)
			}
		default:
			commandOut = io.MultiWriter(commandOut, outWriter)
		}
	}

	if errWriter != nil {
		switch reflect.ValueOf(errWriter).Kind() {
		case reflect.Ptr:
			if !reflect.ValueOf(errWriter).IsNil() {
				commandErr = io.MultiWriter(commandErr, errWriter)
			}
		default:
			commandErr = io.MultiWriter(commandErr, errWriter)
		}
```

fixes the issue. However, I'm not sure what use-case is targeted by the second part of the check. It guards against the following:

```
type writer struct{}

func (w *writer) Write(p []byte) (int, error) {
	if w == nil {
		panic("write on nil receiver")
	}
	return len(p), nil
}

func concreteWriter() *writer {
	return nil
}

func interfaceWriter() io.Writer {
	return concreteWriter()
}

func main() {
	w := interfaceWriter()
	_, err := gexec.Start(exec.Command("whoami"), w, w)
	if err != nil {
		log.Fatal(err)
	}
	time.Sleep(time.Second)
}
```
Output:
```
panic: write on nil receiver
```

But even this is strange, since it's completely sane to have a pointer receiver that could work even if the pointer is nil, e.g.
```go
type writer struct{}

func (w *writer) Write(p []byte) (int, error) {
	return len(p), nil
}
```

So I suggest that `if outWriter != nil` is sufficient as a check.

**Comment by jvshahid** [comment]
@Bo0mer As I started writing a test for this failure, I failed to convince myself that this is something that could be useful in practice, but I am sure you had a use case in mind. Can you share your use case

**Comment by Bo0mer** [comment]
I wanted to discard all output sent to `stderr` when I hit this bug, e.g.
```go
gexec.Start(exec.Command("whoami"), os.Stdout, ioutil.Discard)
```
The code above panics with
```
panic: reflect: call of reflect.Value.IsNil on int Value

goroutine 1 [running]:
reflect.Value.IsNil(0x1107680, 0x129f5b8, 0x82, 0x129f5b8)
	/usr/local/go/src/reflect/value.go:995 +0x12e
github.com/onsi/gomega/gexec.Start(0xc4200bc160, 0x11d2460, 0xc42000c018, 0x11d26a0, 0x129f5b8, 0x0, 0x0, 0x0)
	/Users/ivan/workspace/Go/src/github.com/onsi/gomega/gexec/session.go:85 +0x292
main.main()
	/tmp/gexec/main.go:13 +0x93
exit status 2
```

Cheers,
Ivan
